feat: generic error widget
savannahghi/afya_moja_core pull request #69
Opened 2022-03-08 14:24 UTC by johnngugi

2022-03-08 15:07 UTC, abiudrn approved these changes

2022-03-08 15:09 UTC, abiudrn requested changes

2022-03-08 15:09 UTC, abiudrn commented on lib/src/presentation/generic_error_widget.dart
> +  final double? height;
Is this property being used?

2022-03-08 15:09 UTC, abiudrn commented on lib/src/presentation/generic_error_widget.dart
> +                      largeVerticalSizedBox,
Is this widget necessary, considering this component is supposed to be plugged into other UI elements?

2022-03-09 06:00 UTC, EugeneDevv approved these changes

2022-03-09 06:32 UTC, johnngugi commented on lib/src/presentation/generic_error_widget.dart
> +  final double? height;
Nope.I've removed it

2022-03-09 06:48 UTC, abiudrn approved these changes

2022-03-09 06:48 UTC, merged